# Generated by Django 6.1 on 2026-08-30 03:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe_social_resultado', models.CharField(max_length=200)),
                ('data_teste', models.DateTimeField(auto_now_add=True)),
                ('eleitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_quiz', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
