# Generated by Django 6.1 on 2026-09-10 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_resultadoquiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleitor',
            name='apelido',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
