# Generated by Django 6.1 on 2026-09-13 20:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_eleitor_apelido'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deputadofavorito',
            old_name='nome',
            new_name='nome_deputado',
        ),
        migrations.AddField(
            model_name='deputadofavorito',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deputadofavorito',
            name='foto_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deputadofavorito',
            name='partido',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='eleitor',
            name='codigo_recuperacao',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='eleitor',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='eleitor',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eleitor',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfis/'),
        ),
        migrations.AddField(
            model_name='eleitor',
            name='rg',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='eleitor',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eleitor',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='eleitor',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterUniqueTogether(
            name='deputadofavorito',
            unique_together={('eleitor', 'deputado_id')},
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parlamentar_id', models.IntegerField()),
                ('tipo_parlamentar', models.CharField(choices=[('deputado', 'Deputado'), ('senador', 'Senador')], max_length=20)),
                ('texto', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('eleitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VotoEleitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(choices=[('presidente', 'Presidente'), ('governador', 'Governador'), ('senador', 'Senador'), ('deputado_federal', 'Deputado Federal'), ('deputado_estadual', 'Deputado Estadual'), ('prefeito', 'Prefeito')], max_length=30)),
                ('candidato_id', models.IntegerField()),
                ('nome_candidato', models.CharField(max_length=150)),
                ('partido', models.CharField(blank=True, max_length=50, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('eleitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('eleitor', 'cargo')},
            },
        ),
    ]
